repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: bash -c 'cargo fmt --all'
        language: system
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: bash -c 'cargo clippy --all-targets --all-features -- -D warnings'
        language: system
        pass_filenames: false

      - id: cargo-test
        name: cargo test
        entry: bash -c 'cargo test --all-features --workspace'
        language: system
        pass_filenames: false
